/**
 * Judul chrome (topbar + document.title) per nama rute.
 * Jangan fallback ke "Dashboard" kecuali rute itu memang dashboard.
 *
 * ROUTES_WITH_PAGE_HEADING: halaman yang sudah punya h1/h2 di konten.
 * Topbar tidak mengulang judul yang sama.
 */

import { INVENTORY_TITLE_BY_ROUTE_NAME } from '@/composables/inventory/inventoryRoutes'

function humanizeRouteName(name) {
  if (!name) return 'Halaman'
  return String(name)
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
}

const TITLES = {
  Dashboard: 'Dashboard',
  TeacherDashboard: 'Dashboard Guru',
  TeacherProfile: 'Profil Saya',
  TeacherMyPoints: 'Poin & Prestasi Saya',
  TeacherWali: (auth, route) => {
    const p = String(route?.query?.panel || 'siswa')
    if (p === 'absensi') return 'Absensi Kelas'
    if (p === 'nilai') return 'Nilai Kelas'
    if (p === 'usulan') return 'Usulan Wali'
    if (p === 'jadwal') return 'Jadwal Kelas'
    if (p === 'keuangan') return 'Keuangan Kelas'
    return 'Wali Kelas'
  },
  TeacherMapel: 'Mata Pelajaran',
  TeacherToday: 'Jam Mengajar Hari Ini',
  TeacherSchedule: 'Jadwal Mengajar',
  TeacherAppreciation: 'Apresiasi Guru',
  TeacherLeave: 'Cuti Saya',
  GuruPiket: 'Guru Piket',
  StudentDashboard: 'Dashboard Siswa',
  StudentSchedule: 'Jadwal Saya',
  StudentGrades: 'Nilai Saya',
  StudentViolations: 'Pelanggaran & Prestasi',
  StudentCounseling: 'Konseling',
  StudentUks: 'Kunjungan UKS',
  StudentExtracurricular: 'Ekstrakurikuler',
  StudentPoints: 'Poin Saya',
  StudentProfile: 'Profil Saya',
  SuperAdminDashboard: 'Dashboard Super Admin',
  AppBranding: 'Branding Aplikasi',
  InstitutionAdmins: 'Admin Institusi',
  SuperAdminOnboard: 'Onboarding Sekolah',
  AdoptionMonitoring: 'Monitoring Adopsi',
  BroadcastAnnouncements: 'Broadcast Pengumuman',
  SuperAdminReleaseNotes: 'Catatan Rilis',
  SuperAdminTemplates: 'Library Template Surat',
  AggregateReport: 'Laporan Agregat',
  SystemSettings: 'Pengaturan Sistem',
  SuperAdminMonetization: 'Monetisasi',
  BillingOverview: 'Paket & Add-on',
  Institution: (auth) => (auth?.user?.role === 'super_admin' ? 'Kelola Institusi' : 'Profil Instansi'),
  Student: 'Data Siswa',
  SiswaKeluar: 'Siswa Keluar',
  Teacher: 'Data Guru',
  Kepegawaian: 'Cuti, SK & Jabatan',
  Facility: 'Sarana Prasarana',
  Lab: (auth) => {
    const user = auth?.user
    const perms = user?.permissions || []
    const isLabOnly = user?.is_lab_responsible
      && !perms.includes('facility')
      && user?.role !== 'admin'
      && user?.role !== 'institution_admin'
      && user?.role !== 'super_admin'
    return isLabOnly ? 'Lab Saya' : 'Manajemen Lab'
  },
  LabDetail: 'Detail Lab',
  LabBookingRequest: 'Booking Lab',
  InventoryQrScan: 'Scan QR Inventaris',
  Class: 'Kelas',
  ProgramKeahlian: 'Program Keahlian',
  Report: 'Laporan & Statistik',
  AcademicYear: 'Tahun Ajaran',
  InstitutionChangeRequests: 'Request Perubahan',
  FeedbackTickets: (auth) => (auth?.user?.role === 'super_admin' ? 'Inbox Feedback' : 'Lapor Bug & Request Fitur'),
  StudentChangeRequestsAdmin: 'Permintaan Perubahan Siswa',
  TeacherChangeRequestsAdmin: 'Permintaan Perubahan Pegawai',
  ModuleAccess: 'Akses Modul',
  StudentMutation: 'Mutasi Siswa',
  TeacherMutation: 'Mutasi Guru',
  Notifications: 'Notifikasi',
  AccountSettings: 'Pengaturan Akun',
  AuditLog: 'Audit Log',
  Alumni: 'Alumni',
  LuluskanSiswa: 'Luluskan Siswa',
  NaikKelas: 'Naik Kelas',
  Violation: 'Pelanggaran',
  BkPelanggaran: 'Pelanggaran',
  BkPrestasi: 'Prestasi',
  Counseling: 'Konseling',
  LaporanBk: 'Laporan',
  LaporanPelanggaran: 'Laporan Pelanggaran',
  LaporanPrestasi: 'Laporan Prestasi',
  LaporanApresiasi: 'Laporan Apresiasi',
  Uks: 'Kunjungan UKS',
  UksStock: 'Stok Obat UKS',
  LaporanUks: 'Laporan UKS',
  StudentAttendance: 'Absensi Saya',
  StudentFinance: 'Tagihan & Pembayaran',
  StudentPkl: 'PKL / Jurnal',
  StudentBkk: 'BKK / Lowongan',
  ParentDashboard: 'Portal Orang Tua',
  ParentAnnouncements: 'Pengumuman',
  ParentChildSchedule: 'Jadwal Anak',
  ParentChildGrades: 'Nilai Anak',
  ParentChildAttendance: 'Absensi Anak',
  ParentChildViolations: 'Pelanggaran Anak',
  SchoolContent: 'Berita & Galeri',
  StudentEbooks: 'Perpustakaan Digital',
  Extracurricular: 'Ekstrakurikuler',
  ExtracurricularDetail: 'Detail Ekstrakurikuler',
  IndustryPartners: 'Mitra DU/DI',
  Pkl: 'PKL / Prakerin',
  Bkk: 'BKK / Bursa Kerja',
  Subject: 'Mata Pelajaran',
  LessonSchedule: 'Jadwal Pelajaran',
  TeachingJournal: 'Jurnal Mengajar',
  AttendanceStudent: 'Absensi Siswa',
  AttendanceEmployee: 'Absensi Guru & Staff',
  QrAttendanceScan: 'Scan QR Absensi',
  QrCodeGenerate: 'Generate QR Absensi',
  GradeBook: 'Buku Nilai',
  Raport: 'Raport Siswa',
  RaportKelas: 'Rekap Nilai Kelas',
  BukuInduk: 'Buku Induk',
  OnlineExamList: 'Daftar Ujian',
  OnlineExamCreate: 'Buat Ujian',
  OnlineExamDetail: 'Detail Ujian',
  OnlineExamEdit: 'Edit Ujian',
  OnlineExamSessions: 'Sesi Ujian',
  OnlineExamSessionDetail: 'Detail Sesi Ujian',
  OnlineExamBank: 'Bank Soal',
  OnlineExamBankSoal: 'Soal Bank',
  OnlineExamBankStimulus: 'Stimulus Soal',
  ExamTake: 'Ikuti Ujian',
  Correspondence: 'Buat Surat',
  CorrespondenceTemplates: 'Template Surat',
  CorrespondenceKop: 'Manajemen KOP',
  CorrespondenceTandaTangan: 'Tanda Tangan & Stempel',
  CorrespondenceWorkflow: 'Arsip Persuratan',
  DigitalArchive: 'Arsip Digital',
  AcademicCalendar: 'Kalender Akademik',
  BukuTamu: 'Buku Tamu',
  DocumentPickup: 'Pengambilan Ijazah',
  Library: 'Perpustakaan',
  Semester: 'Manajemen Semester',
  PpdbRingkasan: 'Ringkasan PPDB',
  PpdbKonfigurasi: 'Konfigurasi PPDB',
  PpdbPendaftar: 'Data Pendaftar',
  PpdbPendaftarDetail: 'Detail Pendaftar',
  PpdbStatistik: 'Statistik PPDB',
  PpdbPembayaran: 'Pembayaran PPDB',
  KeuanganJenisBiaya: 'Jenis Biaya',
  KeuanganSpp: 'SPP',
  KeuanganTagihan: 'Tagihan',
  KeuanganPembayaran: 'Pembayaran',
  KeuanganPengeluaran: 'Pengeluaran',
  KeuanganTunggakan: 'Tunggakan',
  KeuanganLaporan: 'Laporan Keuangan',
  PenggajianKomponen: 'Komponen Gaji',
  PenggajianProfil: 'Profil Gaji Pegawai',
  PenggajianPeriode: 'Periode Gaji',
  PenggajianProses: 'Proses Gaji',
  TeacherSlipGaji: 'Slip Gaji Saya',
  ...INVENTORY_TITLE_BY_ROUTE_NAME,
}

/** Rute yang sudah menampilkan judul di dalam halaman (hindari dobel dengan topbar). */
const ROUTES_WITH_PAGE_HEADING = new Set([
  'Dashboard',
  'TeacherDashboard',
  'StudentDashboard',
  'SuperAdminDashboard',
  'ParentDashboard',
  'TeacherProfile',
  'TeacherMyPoints',
  'TeacherToday',
  'TeacherSchedule',
  'TeacherAppreciation',
  'TeacherLeave',
  'Teacher',
  'TeacherMutation',
  'Kepegawaian',
  'ModuleAccess',
  'Institution',
  'Semester',
  'AppBranding',
  'InstitutionAdmins',
  'SuperAdminOnboard',
  'AdoptionMonitoring',
  'BroadcastAnnouncements',
  'SuperAdminReleaseNotes',
  'SuperAdminTemplates',
  'AggregateReport',
  'SystemSettings',
  'SuperAdminMonetization',
  'BillingOverview',
  'FeedbackTickets',
  'Notifications',
  'SchoolContent',
  'DigitalArchive',
  'AcademicCalendar',
  'DocumentPickup',
  'Alumni',
  'SiswaKeluar',
  'LuluskanSiswa',
  'NaikKelas',
  'StudentMutation',
  'ProgramKeahlian',
  'RaportKelas',
  'AttendanceEmployee',
  'AttendanceStudent',
  'QrAttendanceScan',
  'QrCodeGenerate',
  'LabBookingRequest',
  'LabDetail',
  'ExtracurricularDetail',
  'IndustryPartners',
  'Pkl',
  'Bkk',
  'PpdbRingkasan',
  'PpdbKonfigurasi',
  'PpdbPendaftar',
  'PpdbPendaftarDetail',
  'PpdbStatistik',
  'PpdbPembayaran',
  'KeuanganJenisBiaya',
  'KeuanganSpp',
  'KeuanganTagihan',
  'KeuanganPembayaran',
  'KeuanganPengeluaran',
  'KeuanganTunggakan',
  'KeuanganLaporan',
  'PenggajianKomponen',
  'PenggajianProfil',
  'PenggajianPeriode',
  'PenggajianProses',
  'TeacherSlipGaji',
  'OnlineExamList',
  'OnlineExamCreate',
  'OnlineExamEdit',
  'OnlineExamDetail',
  'OnlineExamSessions',
  'OnlineExamSessionDetail',
  'CorrespondenceWorkflow',
  'ParentAnnouncements',
  'ParentChildSchedule',
  'ParentChildGrades',
  'ParentChildAttendance',
  'ParentChildViolations',
  'InventoryQrScan',
  ...Object.keys(INVENTORY_TITLE_BY_ROUTE_NAME),
])

export function resolvePageTitle(routeName, authStore, route) {
  const entry = TITLES[routeName]
  if (typeof entry === 'function') return entry(authStore, route)
  if (entry) return entry
  return humanizeRouteName(routeName)
}

export function routeHasPageHeading(routeName) {
  return ROUTES_WITH_PAGE_HEADING.has(routeName)
}
